title: Mission Quick Guides
description: Mission Guides for FFXI when you just want to get it done.
theme: just-the-docs

url: https://daleterrence.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
